### ISSUE TITLE
Animate on callback

### ISSUE THREAD

**Issue by BDomantas** [kmagiera/react-native-reanimated#128] opened 2018-10-30 20:46 UTC
I am playing around with this package and I came with an issue that animations do not get started on callback. 

I think I am doing this wrong entirely, but here's the idea of what I am trying to achieve and I am seeking for help or ideas how to solve this. 

  I have n number of points along y axis. I get them by measuring views with .measure function 
  provided by react-native. When my draggable box gets dragged to some dropzone I want it to snap 
  to the center of that dropzone. 

code for my y translation
 ```
   this._transY = cond(
      eq(this.state, State.ACTIVE),
      [
        set(this.transY, addY),
        set(this.prevDragY, this.dragY),
        this.transY
      ],
      [
        cond(eq(this.state, State.END), call([addX, absY], this.onDrop)),
        set(this.prevDragY, 0),
        this.transY
      ]
    );
```
my onDrop callback 
```
 onDrop([x, y]) {
    let id = null;
   // just identifying on which dropzone draggable was dropped
    for(let i = 0; i < this.props.dropzones.length; i++) {
      let item = this.props.dropzones[i];
      if( y < item.yPage+item.height && y > item.yPage) {
        id = i;
        break;
      }
    }

   if(id !== null) {
    console.log(this.props.dropzones[id]);
  // this if gets called
  // I identify my dropzone correctly and I have correct coordinates for it here
  // but this block never gets executed and my draggable never animates
    this._transY = block(
    [
      debug('active', this._transY), 
       //these sets might not be correct, please don't mind them
      set(this.transY, add(this.transY, sub(this.props.dropzones[id].yPage, add(this.prevDragY, this.dragY)))),
      set(this.prevDragY, add(this.transY, sub(this.props.dropzones[id].yPage, add(this.prevDragY, this.dragY)))),
      this.transY,
    ]);
   }
  }
```

**Comment by matpaul** [comment] 2018-10-31 15:22
@BDomantas Hi, as i understand flow - with reanimated you can't change this._transY on fly like this  `this._transY = block(`, because you styles already connected to old

**Comment by enesTufekci** [comment] 2018-11-20 16:37
```js
const animationState = new Value(0)
const animation = cond(
  eq(animationState, 0),
  [/* animation on state 0*/],
  [/* animation on state 1*/],
)

const updateAnimationState = () => {
    animationState.setValue(1)
}

```

The power of this library comes from its declarative api. So basically you need to pass every possible condition initially because it will be passed to native UI thread and it will stay there. You can update the nodes from js world and the native UI thread will be informed with that updates.

**Comment by osdnk** [comment] 2018-12-11 22:24
Thanks, @enesTufekci for explaining!

**Closed by osdnk** 2018-12-11 22:24 UTC

**Comment by Kida007** [comment] 2019-04-08 19:55
@enesTufekci I am doing something similar but with **spring** animation , updating animationState is not triggering update.
  As I am new to react-native-reanimated cant really figure out whether a bug or my bad.

I basically have a modal , To which I applied some animations for opening and closing. Its opening like desired , but not closing :(

Animated Values are : 

```
constructor(props) {
    super(props);
    const { x, y, width, height } = props.position;
    this.modalState = new Value(0);

    this.translateX = runSpring(new Value(x), 0, x);
    this.translateY = runSpring(new Value(y), 0, y);
    this.translateWidth = runSpring(new Value(width), wWidth, width);
    this.translateHeight = runSpring(new Value(height), wHeight, height);
  }
```

runSpring function called with _initial value , active destination  , inactive destination_  :
```
runSpring = (translation, activeDest, inactiveDest) => {
  const clock = new Clock();
  const state = {
    finished: new Value(0),
    velocity: new Value(0),
    position: translation,
    time: new Value(0)
  };

  const config = {
    damping: 10,
    mass: 0.3,
    stiffness: 150,
    overshootClamping: false,
    restSpeedThreshold: 0.001,
    restDisplacementThreshold: 0.001
  };

  const activeConfig = { ...config, toValue: activeDest };
  const inactiveConfig = { ...config, toValue: inactiveDest };

  return block([
    cond(clockRunning(clock), 0, startClock(clock)),
    cond(
      eq(this.modalState, 0),
      [spring(clock, state, activeConfig)],
      [spring(clock, state, inactiveConfig)]
    ),
    cond(state.finished, stopClock(clock)),
    state.position
  ]);
};
```

and the updateAnimation function: 
```
 updateAnimation() {
   // closing Modal
    this.modalState.setValue(1);
  }
```

**Comment by enesTufekci** [comment] 2019-04-08 20:28
@Kida007 can you try to passing a new `clock` instance to `runSpring` function. And `runSpring` it doesnt need to be in the class.

e.g 
```js
const translateXClock = new Clock()
this.translateX = runSpring(translateXClock, new Value(x), 0, x);
const translateYClock = new Clock()
this.translateY = runSpring(translateYClock, new Value(y), 0, y);
...
function runSpring(clock, translation, activeDest, inactiveDest) {
 //...
}

```

The source of the problem is 99% clock. Each animation should have its own clock. 

On the other hand, you this case should be done with one animation value. And it can be interpolated in the render method to create all animation styles. Whole animation would be more seamless.

**Comment by Kida007** [comment] 2019-04-08 21:07
Thanks for the quick reply . 

Actually `this.modal` was undefined , cause _runSpring_  was already defined out of the class ( my bad).

Your suggestion above worked , prior to this : I was not using the **declarative power** of the react-native-reanimated. so thanks again.

and also you are right about Interpolation , That is the correct way.

**Comment by enesTufekci** [comment] 2019-04-08 22:06
@Kida007 No problem, my pleasure.
